//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BESTDBEntities : DbContext
    {
        public BESTDBEntities()
            : base("name=BESTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<G_C_Empresa> G_C_Empresa { get; set; }
        public DbSet<G_C_Usuario> G_C_Usuario { get; set; }
        public DbSet<G_D_Usuario_Acceso> G_D_Usuario_Acceso { get; set; }
        public DbSet<G_D_Usuario_Password> G_D_Usuario_Password { get; set; }
        public DbSet<G_C_Modulos> G_C_Modulos { get; set; }
        public DbSet<G_C_Roles> G_C_Roles { get; set; }
        public DbSet<G_C_Tipo_Suscripcion> G_C_Tipo_Suscripcion { get; set; }
        public DbSet<G_D_Empresa_Modulo> G_D_Empresa_Modulo { get; set; }
        public DbSet<G_D_Empresa_Roles> G_D_Empresa_Roles { get; set; }
        public DbSet<G_D_Suscripcion> G_D_Suscripcion { get; set; }
        public DbSet<G_D_Usuario_Roles> G_D_Usuario_Roles { get; set; }
    }
}
