//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BESTDBEntities : DbContext
    {
        public BESTDBEntities()
            : base("name=BESTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<G_C_Empresa> G_C_Empresa { get; set; }
        public DbSet<G_C_Usuario> G_C_Usuario { get; set; }
        public DbSet<G_D_Usuario_Acceso> G_D_Usuario_Acceso { get; set; }
        public DbSet<G_D_Usuario_Password> G_D_Usuario_Password { get; set; }
    }
}
