//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_C_Usuario
    {
        public G_C_Usuario()
        {
            this.G_D_Usuario_Acceso = new HashSet<G_D_Usuario_Acceso>();
            this.G_D_Usuario_Password = new HashSet<G_D_Usuario_Password>();
            this.G_D_Suscripcion = new HashSet<G_D_Suscripcion>();
            this.G_D_Usuario_Roles = new HashSet<G_D_Usuario_Roles>();
        }
    
        public int id_empresa { get; set; }
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string estado { get; set; }
    
        public virtual G_C_Empresa G_C_Empresa { get; set; }
        public virtual ICollection<G_D_Usuario_Acceso> G_D_Usuario_Acceso { get; set; }
        public virtual ICollection<G_D_Usuario_Password> G_D_Usuario_Password { get; set; }
        public virtual ICollection<G_D_Suscripcion> G_D_Suscripcion { get; set; }
        public virtual ICollection<G_D_Usuario_Roles> G_D_Usuario_Roles { get; set; }
    }
}
