//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_C_Usuario
    {
        public G_C_Usuario()
        {
            this.G_D_Usuario_Acceso = new HashSet<G_D_Usuario_Acceso>();
            this.G_D_Usuario_Password = new HashSet<G_D_Usuario_Password>();
        }
    
        public int id_empresa { get; set; }
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string estado { get; set; }
    
        public virtual G_C_Empresa G_C_Empresa { get; set; }
        public virtual ICollection<G_D_Usuario_Acceso> G_D_Usuario_Acceso { get; set; }
        public virtual ICollection<G_D_Usuario_Password> G_D_Usuario_Password { get; set; }
    }
}
