//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_C_Tipo_Suscripcion
    {
        public G_C_Tipo_Suscripcion()
        {
            this.G_D_Suscripcion = new HashSet<G_D_Suscripcion>();
        }
    
        public int id_tipo_suscripcion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<G_D_Suscripcion> G_D_Suscripcion { get; set; }
    }
}
