//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class G_C_Empresa
    {
        public G_C_Empresa()
        {
            this.G_C_Usuario = new HashSet<G_C_Usuario>();
            this.G_D_Empresa_Modulo = new HashSet<G_D_Empresa_Modulo>();
            this.G_D_Empresa_Roles = new HashSet<G_D_Empresa_Roles>();            
        }

        [DisplayName("Código de Empresa")]
        public int id_empresa { get; set; }

        [DisplayName("Razón Social")]
        public string razon_social { get; set; }

        [DisplayName("Nombre Comercial")]
        public string nombre_comercial { get; set; }

        [DisplayName("Dirección")]
        public string direccion { get; set; }

        [DisplayName("Email")]
        public string email { get; set; }

        [DisplayName("Teléfono")]
        public string telefono { get; set; }

        [DisplayName("Fecha Registro")]
        public System.DateTime fecha_registro { get; set; }

        [DisplayName("Estado")]
        public string estado { get; set; }
    
        public virtual ICollection<G_C_Usuario> G_C_Usuario { get; set; }
        public virtual ICollection<G_D_Empresa_Modulo> G_D_Empresa_Modulo { get; set; }
        public virtual ICollection<G_D_Empresa_Roles> G_D_Empresa_Roles { get; set; }
    }
}
