//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class G_C_Empresa
    {
        public G_C_Empresa()
        {
            this.G_C_Usuario = new HashSet<G_C_Usuario>();
        }
        
        [DisplayName("Empresa")]
        public int id_empresa { get; set; }

        [DisplayName("Razon Social")]
        public string razon_social { get; set; }

        [DisplayName("Nombre Comercial")]
        public string nombre_comercial { get; set; }

        [DisplayName("Direccion")]
        public string direccion { get; set; }

        [DisplayName("Correo")]
        public string email { get; set; }

        [DisplayName("PBX")]
        public string telefono { get; set; }

        [DisplayName("Fecha registro")]
        public System.DateTime fecha_registro { get; set; }

        [DisplayName("Estado")]
        public string estado { get; set; }
    
        public virtual ICollection<G_C_Usuario> G_C_Usuario { get; set; }
    }
}
