//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_D_Empresa_Roles
    {
        public int id_empresa { get; set; }
        public int id_rol { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string estado { get; set; }
    
        public virtual G_C_Empresa G_C_Empresa { get; set; }
        public virtual G_C_Roles G_C_Roles { get; set; }
    }
}
